### ISSUE TITLE
语句末尾字符会被错误的替换

### ISSUE THREAD

**Issue by fwhappy** [importcjj/sensitive#1]
代码：
fmt.Println(filter.Replace("hello", 42))
fmt.Println(filter.Replace("hello world", 42))
fmt.Println(filter.Replace("人", 42))
fmt.Println(filter.Replace("不办人事  人", 42))

输出结果：
hell*
hello worl*
*
****  *

**Comment by importcjj** [comment]
我用这个试了下没问题啊。
你能提供完整代码吗？

**Comment by fwhappy** [comment]
package main

import (
	"fmt"

	"github.com/importcjj/sensitive"
)

func main() {
	filter := sensitive.New()
	filter.LoadWordDict("./dict.txt")
	filter.AddWord("长者")

	fmt.Println(filter.Replace("我为长者续一秒", 42)) // 我为**续一秒
	fmt.Println(filter.Replace("hello", 42))
	fmt.Println(filter.Replace("hello world", 42))

}

就是你提供的示例代码，dict我拿出来了

我用的是mac os，go 版本是1.8

**Comment by fwhappy** [comment]
在centos环境下试了一下，没什么问题 ，😓

**Comment by fwhappy** [comment]
试了一下，centos环境也有问题
如果不Load dict.txt就是正常的，load后就出错了

**Comment by liyue201** [comment]
“的”全部变*了
