### ISSUE TITLE
A more serious readme is required

### ISSUE THREAD

**Issue by xuezhaojun** [importcjj/sensitive#12]
Hello, 

Your project is great, the code is easy to understand and use, however, the ReadMe of this project seems to be funny but not that professional.

I want to use this lib but a little worried about Code Review. Are you guys considering make an Readme/doc for all users from many other countries?

Thanks for your hard work, it helps a lot

**Comment by importcjj** [comment]
Ok, I know what you mean, I will delete the unwelcome content.
