### ISSUE TITLE
如何释放一个Trim树，重新载入

### ISSUE THREAD

**Issue by mingzaily** [importcjj/sensitive#18]
功能：程序初始化载入到word，后续请求使用word这个指针直接处理即可。但又需要定时刷新词库，但如果重新AddWord会导致内存上涨，如何先释放后重新addWord

**Comment by importcjj** [comment]
自己再包一层呗，树对象作为新对象的内部字段，刷新词库就直接新建树对象替换就好了啊。如果有并发就再加个锁
