### ISSUE TITLE
关键词过滤问题

### ISSUE THREAD

**Issue by tangbingbing** [importcjj/sensitive#3]
你的这个库在本地环境使用关键字过滤是正常的,放到服务器的时候就用不了
服务上使用关键查询不管输入什么内容 都是匹配关键字成功 可是匹配出来的关键字是空

**Comment by importcjj** [comment]
你好 是否方便提供下服务器环境 以及使用的函数和输入输出，以便我查找问题。谢谢！

**Comment by tangbingbing** [comment]
![image](https://user-images.githubusercontent.com/16116559/43354922-7e0f268a-9286-11e8-84ad-d9950c906ef2.png)
![image](https://user-images.githubusercontent.com/16116559/43354948-aaee33f8-9286-11e8-885b-1b732fd03676.png)
使用 CoreOS 7  nginx go环境 beego 框架

**Comment by importcjj** [comment]
好的 等我空下来就立马试试

**Comment by importcjj** [comment]
@tangbingbing  你好问题我找到了。原因是上一次更新的时候添加了[Validate](https://github.com/importcjj/sensitive/blob/master/trie_tree.go#L116)这个函数，用于验证一个字符串是否合法，即无关键词的时候返回True和空字符串，代表为合法字符串。然后FindIn内部使用了该函数导致无关键词的时候返回了True。。。

**Comment by importcjj** [comment]
@tangbingbing 还有一点就是filter最好以全局变量的形式存在

**Comment by giskook** [comment]
@importcjj filter是线程安全的吧？

**Comment by importcjj** [comment]
@giskook 添加敏感词并非线程安全，可以自己封装控制

**Comment by giskook** [comment]
@importcjj 读取是线程安全的吗？

**Comment by importcjj** [comment]
> @importcjj 读取是线程安全的吗？

是的
