### ISSUE TITLE
LoadWordDict无法加载文件

### ISSUE THREAD

**Issue by coldwarm7** [importcjj/sensitive#4]
open ../dict/dict.txt: The system cannot find the path specified.

很奇怪的一件事，无法加载显示ioutil.ReadFile(path)这里出错，但是我自己重新写了一个加载文件的方法，采用绝对路径，可以加载成功，不知道问题出在哪里

**Comment by importcjj** [comment]
相对路径是根据你程序的路径来确定。

**Comment by coldwarm7** [comment]
采用相对路径filter.LoadWordDict("../dict/dict.txt")加载不成功，open ../dict/dict.txt: The system cannot find the path specified.即使我写的那个加载文件的方法，也只能采用绝对路径，相对路径同样加载不到

**Comment by importcjj** [comment]
根本问题是你的目录中没有dict。正确的做法是: 把我仓库中的dict.txt下载下来，然后放在你自己的程序目录，使用filter.LoadWordDict("dict.txt")来加载。

**Comment by coldwarm7** [comment]
不是这样的，如果您不忙的话可以看一下我的代码https://github.com/coldwarm7/go-demo/blob/master/demo/SensitiveDemo.go  ，我还把您的代码直接clone下来在源代码上运行也加载不出来

**Comment by importcjj** [comment]
什么环境？

**Comment by coldwarm7** [comment]
go 1.11.2 idea下运行的

**Comment by importcjj** [comment]
我想应该是windows的文件路径和linux的路径表示不同造成的。

试试用filepath把路径兼容windows

```golang
import "path/filepath"

tree := sensitive.New()
tree.LoadWordDict(filepath.FromSlash("../txt/dict.txt"))
```

**Comment by coldwarm7** [comment]
还是不行
```
	dict,err := GetFileContentAsStringLines("txt/dict.txt")
	fmt.Println(err)
	for _,value := range dict{
		tree.AddWord(value)
	}
```
```
func GetFileContentAsStringLines(filePath string) ([]string, error) {
	result := []string{}
	b, err := ioutil.ReadFile(filePath)
	if err != nil {
		return result, err
	}
	s := string(b)
	for _, lineStr := range strings.Split(s, "\n") {
		lineStr = strings.TrimSpace(lineStr)
		if lineStr == "" {
			continue
		}
		result = append(result, lineStr)
	}
	return result, nil
}
```
这样加载是可行的

**Comment by importcjj** [comment]
再问一下 你是怎么运行程序的 完整流程？idea我没用过, 你能确定你的程序运行的目录是go文件所在的目录吗

**Comment by importcjj** [comment]
如果
` GetFileContentAsStringLines("txt/dict.txt")` 可行的话
`filter.LoadWordDict("txt/dict.txt")`应该也是可行的

**Comment by coldwarm7** [comment]
这么说的话，我大概知道是为什么了，idea运行go程序会在idea自己的目录下进行构建，之前运行程序的时候也碰到过找不到前端模板的情况，我可能需要直接在cmd命令行`go build`来进行程序的构建。
但是即便这样，我仍然找不到`filter.LoadWordDict("txt/dict.txt")`失败的原因
![](http://coldwarm7.oss-cn-beijing.aliyuncs.com/19-1-9/51738362.jpg)
![](http://coldwarm7.oss-cn-beijing.aliyuncs.com/19-1-9/44381017.jpg)

**Comment by importcjj** [comment]
我看你这个路径怎么是/txt/dict.txt? 是写错了吗

**Comment by coldwarm7** [comment]
我是智障，改了路径之后debug发现文件可以加载了，但是
![](http://coldwarm7.oss-cn-beijing.aliyuncs.com/19-1-9/27905980.jpg)
好像还是无法实现过滤

**Comment by importcjj** [comment]
试试在过滤前手动添加敏感词呢 tree.AddWord("C4", "服务", "TMD")

**Comment by coldwarm7** [comment]
![](http://coldwarm7.oss-cn-beijing.aliyuncs.com/19-1-9/14053504.jpg)
手动添加没问题的
---
debug显示文件是加载了的
![](http://coldwarm7.oss-cn-beijing.aliyuncs.com/19-1-9/42428515.jpg)

**Comment by importcjj** [comment]
那应该是字典文件换行符的问题 稍等 我试一下

**Comment by importcjj** [comment]
你好 拉一下最新的代码

**Comment by coldwarm7** [comment]
可以了，谢谢大佬

**Comment by importcjj** [comment]
哈哈哈 还得感谢你帮我发现了新问题呢
